name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: make install

    - name: Run lint
      run: make lint

    - name: Build project
      run: make build

    - name: Run tests
      run: make test

    - name: Clean project
      run: make clean
