name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Specify the Node.js version you are using

    - name: Install dependencies
      run: make install

    - name: Run lint
      run: make lint

    - name: Run tests
      run: make test

    - name: Build project
      run: make build
